'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmDetalheSolicitacaoChaveAcesso

    '''<summary>
    '''txtDataSolicitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSolicitacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStatusSolicitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusSolicitacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCNPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCNPJ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRazaoSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRazaoSocial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNomeSolicitante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeSolicitante As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmailSolicitante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailSolicitante As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btVoltar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btVoltar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btValidar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btValidar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btFecharPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btFecharPopUp As Global.System.Web.UI.WebControls.Button
End Class
