'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Login

    '''<summary>
    '''lblQtdSolicCadPendentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQtdSolicCadPendentes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQtdSolicCadValidadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQtdSolicCadValidadas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQtdSolicAltPendentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQtdSolicAltPendentes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQtdSolicAltValidadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQtdSolicAltValidadas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQtdSolicChavePendentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQtdSolicChavePendentes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQtdSolicChaveValidadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQtdSolicChaveValidadas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btFecharPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btFecharPopUp As Global.System.Web.UI.WebControls.Button
End Class
