'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucrContentTop

    '''<summary>
    '''MenuInterno_001 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuInterno_001 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MenuInterno_002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuInterno_002 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MenuInterno_003 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuInterno_003 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MenuInterno_004 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuInterno_004 As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
