'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default1

    '''<summary>
    '''txtCNPJCadastramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCNPJCadastramento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btEnviarCadastramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btEnviarCadastramento As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtCNPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCNPJ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtChaveAcesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChaveAcesso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btAcessoFornecedores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAcessoFornecedores As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btFecharPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btFecharPopUp As Global.System.Web.UI.WebControls.Button
End Class
